/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IconWrapper: typeof import('./src/components/IconWrapper.vue')['default']
    Play: typeof import('./src/components/play/Play.vue')['default']
    PlayList: typeof import('./src/components/playList/PlayList.vue')['default']
    PlayListEdit: typeof import('./src/components/playList/PlayListEdit.vue')['default']
    PlayListList: typeof import('./src/components/playList/PlayListList.vue')['default']
    PlayRuleEdit: typeof import('./src/components/play/PlayRuleEdit.vue')['default']
    PlayRuleList: typeof import('./src/components/play/PlayRuleList.vue')['default']
  }
}
